[package]
name = "wasi_snapshot_preview1"
version = "0.0.0"
edition.workspace = true

[dependencies]
wasi = "0.11.0"
wit-bindgen-guest-rust = { workspace = true }

[lib]
crate-type = ["cdylib"]
test = false
